name: learn-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - abseil-cpp=20200225.2=ha925a31_2
  - aiohttp=3.6.3=py38h1e8a9f7_2
  - argon2-cffi=20.1.0=py38h294d835_2
  - arrow-cpp=0.15.1=py38h47fa567_6
  - arviz=0.10.0=py_0
  - async-timeout=3.0.1=py_1000
  - async_generator=1.10=py_0
  - atomicwrites=1.4.0=py_0
  - attrs=20.2.0=pyh9f0ad1d_0
  - aws-c-common=0.4.59=h8ffe710_1
  - aws-c-event-stream=0.1.6=h9490e6b_5
  - aws-checksums=0.1.9=h25771f4_2
  - aws-sdk-cpp=1.8.70=he2782d2_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - beautifulsoup4=4.9.3=pyhb0f4dca_0
  - blas=1.0=mkl
  - bleach=3.2.1=pyh9f0ad1d_0
  - boost-cpp=1.67.0=hea38baa_0
  - boto=2.49.0=py_0
  - boto3=1.15.16=pyh9f0ad1d_0
  - botocore=1.18.16=pyh9f0ad1d_0
  - branca=0.4.1=py_0
  - brotli=1.0.9=h8ffe710_5
  - brotli-bin=1.0.9=h8ffe710_5
  - brotlipy=0.7.0=py38h294d835_1001
  - bz2file=0.98=py_0
  - bzip2=1.0.8=h8ffe710_4
  - c-ares=1.16.1=he774522_3
  - ca-certificates=2021.10.8=h5b45459_0
  - cachetools=4.1.1=py_0
  - certifi=2021.10.8=py38haa244fe_1
  - cffi=1.14.3=py38h0e640b1_1
  - cftime=1.2.1=py38h1e00858_1
  - chardet=3.0.4=py38h9bdc248_1008
  - clang=11.0.0=h57928b3_2
  - clang-11=11.0.0=default_h5c34c98_2
  - clangxx=11.0.0=default_h5c34c98_2
  - click=7.1.2=pyh9f0ad1d_0
  - colorama=0.4.3=py_0
  - compiler-rt=11.0.0=h2e52968_2
  - compiler-rt_win-64=11.0.0=h587dcfd_2
  - convertdate=2.2.2=pyh9f0ad1d_0
  - cryptography=3.1.1=py38h0e640b1_1
  - curl=7.71.1=h86230a5_2
  - cvxpy=1.1.6=py38h7ae7562_0
  - cvxpy-base=1.1.6=py38h251f6bf_0
  - cycler=0.10.0=py_2
  - cython=0.29.21=py38h885f38d_2
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - docutils=0.15.2=py38haa244fe_2
  - double-conversion=3.1.5=h0e60522_2
  - ecos=2.0.7.post1=py38h347fdf6_4
  - entrypoints=0.3=pyhd8ed1ab_1003
  - ephem=3.7.7.1=py38h1e8a9f7_1
  - et_xmlfile=1.0.1=py_1001
  - fbprophet=0.7.1=py38h7ae7562_0
  - folium=0.11.0=py_0
  - freetype=2.10.3=hd328e21_0
  - fsspec=2021.11.0=pyhd8ed1ab_0
  - future=0.18.2=py38haa244fe_3
  - gensim=3.8.3=py38h885f38d_4
  - gflags=2.2.2=ha925a31_1004
  - glog=0.4.0=h0174b99_3
  - google-api-core=1.22.2=py38h21ff451_0
  - google-auth=1.22.0=py_0
  - google-cloud-core=1.4.3=pyh9f0ad1d_0
  - google-cloud-storage=1.31.2=pyh9f0ad1d_0
  - google-crc32c=1.0.0=py38h0523e21_1
  - google-resumable-media=1.1.0=pyh9f0ad1d_0
  - googleapis-common-protos=1.52.0=py38h5b57dd5_1
  - graphviz=2.38=hfd603c8_2
  - grpc-cpp=1.26.0=h9f84659_0
  - grpcio=1.31.0=py38h735fc1f_0
  - hdf4=4.2.13=h0e5069d_1005
  - hdf5=1.10.6=nompi_h5268f04_1112
  - holidays=0.10.3=pyh9f0ad1d_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - idna=2.10=pyh9f0ad1d_0
  - imbalanced-learn=0.7.0=py_1
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2019.4=245
  - ipykernel=5.3.4=py38h7b7c402_1
  - ipython=7.18.1=py38h1cdfbd6_1
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=pyh9f0ad1d_1
  - jdcal=1.4.1=py_0
  - jedi=0.17.2=py38haa244fe_1
  - jmespath=0.10.0=pyh9f0ad1d_0
  - joblib=0.17.0=py_0
  - jpeg=9d=h8ffe710_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter=1.0.0=py38haa244fe_6
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_contrib_core=0.3.3=py_2
  - jupyter_contrib_nbextensions=0.5.1=pyhd8ed1ab_2
  - jupyter_core=4.6.3=py38haa244fe_2
  - jupyter_highlight_selected_word=0.2.0=py38haa244fe_1002
  - jupyter_latex_envs=1.4.6=pyhd8ed1ab_1002
  - jupyter_nbextensions_configurator=0.4.1=py38haa244fe_2
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - kiwisolver=1.2.0=py38h95a2b95_1
  - korean_lunar_calendar=0.2.1=pyh9f0ad1d_0
  - krb5=1.18.2=hc04afaa_0
  - lcms2=2.11=h6a326e1_1
  - libblas=3.8.0=14_mkl
  - libboost=1.67.0=hd9e427e_4
  - libbrotlicommon=1.0.9=h8ffe710_5
  - libbrotlidec=1.0.9=h8ffe710_5
  - libbrotlienc=1.0.9=h8ffe710_5
  - libcblas=3.8.0=14_mkl
  - libcrc32c=1.1.1=h0e60522_2
  - libcurl=7.71.1=h86230a5_2
  - libiconv=1.16=he774522_0
  - liblapack=3.8.0=14_mkl
  - libnetcdf=4.7.4=nompi_h3a9aa94_107
  - libpng=1.6.37=h1d00b33_2
  - libprotobuf=3.11.2=h1a1b453_0
  - libpython=2.0=py38haa244fe_1
  - libsodium=1.0.18=h8d14728_1
  - libssh2=1.9.0=hb06d900_5
  - libtiff=4.1.0=h56a325e_0
  - libxml2=2.9.10=hf5bbc77_4
  - libxslt=1.1.33=h65864e5_2
  - lunarcalendar=0.0.9=py_0
  - lxml=4.6.1=py38he3d0fc9_0
  - lz4=3.1.3=py38h2bbff1b_0
  - lz4-c=1.8.1.2=h2fa13f4_0
  - m2w64-binutils=2.25.1=5
  - m2w64-bzip2=1.0.6=6
  - m2w64-crt-git=5.0.0.4636.2595836=2
  - m2w64-gcc=5.3.0=6
  - m2w64-gcc-ada=5.3.0=6
  - m2w64-gcc-fortran=5.3.0=6
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gcc-objc=5.3.0=6
  - m2w64-gmp=6.1.0=2
  - m2w64-headers-git=5.0.0.4636.c0ad18a=2
  - m2w64-isl=0.16.1=2
  - m2w64-libiconv=1.14=6
  - m2w64-libmangle-git=5.0.0.4509.2e5a9a2=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-make=4.1.2351.a80a8b8=2
  - m2w64-mpc=1.0.3=3
  - m2w64-mpfr=3.1.4=4
  - m2w64-pkg-config=0.29.1=2
  - m2w64-toolchain=5.3.0=7
  - m2w64-toolchain_win-64=2.4.0=0
  - m2w64-tools-git=5.0.0.4592.90b8472=2
  - m2w64-windows-default-manifest=6.4=3
  - m2w64-winpthreads-git=5.0.0.4634.697f757=2
  - m2w64-zlib=1.2.8=10
  - matplotlib=3.3.1=1
  - matplotlib-base=3.3.1=py38hfb9ee82_1
  - mistune=0.8.4=py38h294d835_1004
  - mkl=2019.4=245
  - mkl-service=2.3.0=py38hfa6e2cd_0
  - mkl_fft=1.2.0=py38h45dec08_0
  - mkl_random=1.1.0=py38he350917_0
  - more-itertools=8.8.0=pyhd3eb1b0_0
  - msys2-conda-epoch=20160418=1
  - multidict=4.7.5=py38h294d835_2
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py38haa244fe_3
  - nbformat=5.0.8=py_0
  - nest-asyncio=1.4.1=py_0
  - netcdf4=1.5.4=nompi_py38h87f19a6_103
  - networkx=2.5.1=pyhd8ed1ab_0
  - nltk=3.5=pyhd8ed1ab_1
  - notebook=6.1.4=py38h32f6830_1
  - olefile=0.46=pyh9f0ad1d_1
  - openpyxl=3.0.5=py_0
  - openssl=1.1.1l=h8ffe710_0
  - osqp=0.6.1=py38he6e81aa_2
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.1.3=py38h3ef910b_2
  - pandasql=0.7.3=pyhd8ed1ab_0
  - pandoc=2.11.4=h8ffe710_0
  - pandocfilters=1.4.2=py_1
  - parso=0.7.0=pyh9f0ad1d_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.0.0=py38h1d4d63c_0
  - pip=20.2.3=py_0
  - plotly=4.11.0=pyh9f0ad1d_0
  - pluggy=0.13.1=py38haa95532_0
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.8=pyha770c72_0
  - prompt_toolkit=3.0.8=hd8ed1ab_0
  - protobuf=3.11.2=py38he025d50_0
  - ptyprocess=0.6.0=py_1001
  - py=1.10.0=pyhd3eb1b0_0
  - py4j=0.10.9=pyh9f0ad1d_0
  - pyarrow=0.15.1=py38h47e9c7a_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.7.1=py_0
  - pymeeus=0.3.7=pyh9f0ad1d_0
  - pymongo=3.11.0=py38h885f38d_4
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.9.2=py38ha925a31_4
  - pyreadline=2.1=py38haa244fe_1003
  - pyrsistent=0.17.3=py38h294d835_2
  - pysocks=1.7.1=py38haa244fe_3
  - pyspark=3.0.0=py_0
  - pystan=2.19.1.1=py38h02adce6_3
  - pytest=6.2.4=py38haa95532_2
  - python=3.8.5=h60c2a47_9_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=2_cp38
  - pytz=2020.1=pyh9f0ad1d_0
  - pywin32=227=py38h294d835_1
  - pywinpty=0.5.7=py38haa244fe_1
  - pyyaml=5.3.1=py38h294d835_2
  - pyzmq=19.0.2=py38h77b9d75_2
  - qt=5.9.7=hc6833c9_1
  - qtconsole=4.7.7=pyh9f0ad1d_0
  - qtpy=1.9.0=py_0
  - re2=2019.08.01=vc14h6538335_0
  - regex=2020.10.15=py38h1e8a9f7_0
  - requests=2.24.0=pyh9f0ad1d_0
  - retrying=1.3.3=py_2
  - rsa=4.6=pyh9f0ad1d_0
  - s3fs=0.4.2=py_0
  - s3transfer=0.3.3=pyhd8ed1ab_5
  - scikit-learn=0.23.2=py38ha09990b_3
  - scikit-surprise=1.1.1=py38h1e00858_1
  - scipy=1.5.0=py38h9439919_0
  - scs=2.1.2=py38h7465cd0_2
  - seaborn=0.11.0=h57928b3_1
  - seaborn-base=0.11.0=pyhd8ed1ab_1
  - send2trash=1.5.0=py_0
  - setuptools=50.3.0=py38haa95532_1
  - setuptools-git=1.2=py_1
  - simplegeneric=0.8.1=py_1
  - sip=4.19.13=py38ha925a31_0
  - six=1.15.0=pyh9f0ad1d_0
  - smart_open=3.0.0=pyh9f0ad1d_0
  - snappy=1.1.8=ha925a31_3
  - soupsieve=2.0.1=py_1
  - sqlalchemy=1.3.19=py38h1e8a9f7_1
  - sqlite=3.33.0=he774522_1
  - terminado=0.9.1=py38haa244fe_1
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - thrift-cpp=0.11.0=h1ebf3fd_3
  - tk=8.6.10=h8ffe710_1
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.0.4=py38h1e8a9f7_2
  - tqdm=4.50.2=pyh9f0ad1d_0
  - traitlets=5.0.5=py_0
  - uriparser=0.9.3=he025d50_1
  - urllib3=1.25.10=py_0
  - vc=14.1=h869be7e_1
  - vs2015_runtime=14.16.27012=h30e32a0_2
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.35.1=pyh9f0ad1d_0
  - widgetsnbextension=3.5.1=py38haa244fe_4
  - win_inet_pton=1.1.0=py38haa244fe_2
  - wincertstore=0.2=py38haa244fe_1006
  - winpty=0.4.3=4
  - xarray=0.16.1=py_0
  - xlrd=1.2.0=pyh9f0ad1d_1
  - xz=5.2.5=h62dcd97_1
  - yaml=0.2.5=he774522_0
  - yarl=1.5.1=py38h1e8a9f7_0
  - zeromq=4.3.2=h0e60522_5
  - zipp=3.3.0=py_0
  - zlib=1.2.11=h62dcd97_1010
  - zstd=1.3.7=haafe652_1001
  - pip:
    - absl-py==0.10.0
    - astunparse==1.6.3
    - celluloid==0.2.0
    - country-converter==0.7.4
    - flask==2.0.2
    - gast==0.3.3
    - geographiclib==1.52
    - geopy==2.2.0
    - geos==0.2.3
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - h5py==2.10.0
    - itsdangerous==2.0.1
    - jinja2==3.0.3
    - keras==2.4.3
    - keras-preprocessing==1.1.2
    - markdown==3.3.2
    - markupsafe==2.0.1
    - numpy==1.21.4
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - orc==0.1.0
    - patsy==0.5.2
    - pmdarima==1.8.4
    - pybind11==2.5.0
    - pygeocoder==1.2.5
    - pyshp==2.1.3
    - python-graphviz==0.17
    - requests-oauthlib==1.3.0
    - reverse-geocoder==1.5.1
    - shapely==1.8.0
    - statsmodels==0.13.0
    - tensorboard==2.3.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.3.1
    - tensorflow-estimator==2.3.0
    - termcolor==1.1.0
    - werkzeug==2.0.2
    - wrapt==1.12.1
    - xgboost==1.2.1
prefix: F:\Flatiron\Anaconda2\envs\learn-env
